### ISSUE TITLE
🚀 [Feature] Implement New Internal Pages

### ISSUE THREAD

**Issue by Tirokk** [sender-fm/Sender-Fm-Ocelot-Social-Deploy-Rebranding#5]
## 💥 Feature

Implement new internal pages.

- having the radio player on the landing page

### Todo

- [ ] use sender.fm font in organisation page
- [ ] maybe the others as well?
- [ ] care for mobile view of the organisation players
- [x] remove `ocelot.sender.fm` from the values.yaml
- [ ] delete `ocelot.sender.fm` from the providers subdomains as well

**Comment by Tirokk** [comment]
for the leftovers see #8
